<script language="VBScript" runat="server" Explicit="True"  Buffer = "true" ExpiresAbsolute="DateTime.Now.AddDays(-365d)">
	'public Function CommentsSettings()
	'If bolSendMultiple=True Then
	'strMailName = UCase(Mid(SendToMultiple, InStrRev(SendToMultiple, "@") + 1))
	'If InStrRev(strMailName, ")") Then
	'strMailName = Replace(strMailName, ")", "")
	'End if
	'If InStrRev(strMailName, ";") Then
	'strMailName = Replace(strMailName, ";", "")
	'End if
	'strMailName = Trim(strMailName)
	'Else
	'strMailName = UCase(Mid(SendToAddress, InStrRev(SendToAddress, "@") + 1))
	'End if

	'Select Case strMailName
	'Case "CCRCHOPE.COM"
	'strMailName =  "CCRCHOPE.COM"
	'Case "GMACRFC.COM"
	'strMailName =  "GMACRFC.COM"
	'Case "RFC.COM"
	'strMailName = "RFC.COM"
	'Case "HOMECOMINGS.COM"
	'strMailName = "HOMECOMINGS.COM"
	'Case "HFWHOLESALE.COM"
	'strMailName = "HFWHOLESALE.COM"
	'Case "RESMONEY.COM"
	'strMailName = "RESMONEY.COM"
	'Case "RMCWHOLESALE.COM"
	'strMailName = "RMCWHOLESALE.COM"
	'Case "GMACRFC.CO.UK"
	'strMailName =  "GMACRFC.CO.UK"
	'Case "GMACMH.COM"
	'strMailName =  "GMACMH.COM"
	'Case ""
	'strMailName = ""
	'     Case Else
	'	strErrorMessage = "The comment cannot be sent because the Send To email address or addresses are outside the RFC domain." & "<br>" & "<br>" & _
'            "<b>WebName:</b> " & WebName & "<br>" & _
'            "<b>Send To Name:</b> " & SendToName & "<br>" & _
'            "<b>Send To Address:</b> " & SendToAddress & "<br><br>" & _
'            "Contact support for help in resolving the problem."
'            WriteErrorMessage
'            response.end
'End Select

'Previous variable names:
'myRestrictDomain = strMailName
'myWebMasterDomain = strMailName
'End Function-->
</Script>





