//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace HPF.FutureState.WebService.Test.Web.HPFCallCenterService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CallCenterServiceSoap", Namespace="https://www.homeownershopenetwork.org")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseDTO))]
    public partial class CallCenterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthenticationInfo authenticationInfoValueField;
        
        private System.Threading.SendOrPostCallback SaveCallLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveCallLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchForeClosureCaseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CallCenterService() {
            this.Url = global::HPF.FutureState.WebService.Test.Web.Properties.Settings.Default.HPF_FutureState_WebService_Test_Web_HPFCallCenterService_CallCenterService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationInfo AuthenticationInfoValue {
            get {
                return this.authenticationInfoValueField;
            }
            set {
                this.authenticationInfoValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveCallLogCompletedEventHandler SaveCallLogCompleted;
        
        /// <remarks/>
        public event RetrieveCallLogCompletedEventHandler RetrieveCallLogCompleted;
        
        /// <remarks/>
        public event SearchForeClosureCaseCompletedEventHandler SearchForeClosureCaseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.homeownershopenetwork.org/SaveCallLog", RequestNamespace="https://www.homeownershopenetwork.org", ResponseNamespace="https://www.homeownershopenetwork.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CallLogInsertResponse SaveCallLog(CallLogInsertRequest request) {
            object[] results = this.Invoke("SaveCallLog", new object[] {
                        request});
            return ((CallLogInsertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SaveCallLogAsync(CallLogInsertRequest request) {
            this.SaveCallLogAsync(request, null);
        }
        
        /// <remarks/>
        public void SaveCallLogAsync(CallLogInsertRequest request, object userState) {
            if ((this.SaveCallLogOperationCompleted == null)) {
                this.SaveCallLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCallLogOperationCompleted);
            }
            this.InvokeAsync("SaveCallLog", new object[] {
                        request}, this.SaveCallLogOperationCompleted, userState);
        }
        
        private void OnSaveCallLogOperationCompleted(object arg) {
            if ((this.SaveCallLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCallLogCompleted(this, new SaveCallLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.homeownershopenetwork.org/RetrieveCallLog", RequestNamespace="https://www.homeownershopenetwork.org", ResponseNamespace="https://www.homeownershopenetwork.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CallLogRetrieveResponse RetrieveCallLog(CallLogRetrieveRequest request) {
            object[] results = this.Invoke("RetrieveCallLog", new object[] {
                        request});
            return ((CallLogRetrieveResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveCallLogAsync(CallLogRetrieveRequest request) {
            this.RetrieveCallLogAsync(request, null);
        }
        
        /// <remarks/>
        public void RetrieveCallLogAsync(CallLogRetrieveRequest request, object userState) {
            if ((this.RetrieveCallLogOperationCompleted == null)) {
                this.RetrieveCallLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveCallLogOperationCompleted);
            }
            this.InvokeAsync("RetrieveCallLog", new object[] {
                        request}, this.RetrieveCallLogOperationCompleted, userState);
        }
        
        private void OnRetrieveCallLogOperationCompleted(object arg) {
            if ((this.RetrieveCallLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveCallLogCompleted(this, new RetrieveCallLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.homeownershopenetwork.org/SearchForeClosureCase", RequestNamespace="https://www.homeownershopenetwork.org", ResponseNamespace="https://www.homeownershopenetwork.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ForeClosureCaseSearchResponse SearchForeClosureCase(ForeClosureCaseSearchRequest request) {
            object[] results = this.Invoke("SearchForeClosureCase", new object[] {
                        request});
            return ((ForeClosureCaseSearchResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SearchForeClosureCaseAsync(ForeClosureCaseSearchRequest request) {
            this.SearchForeClosureCaseAsync(request, null);
        }
        
        /// <remarks/>
        public void SearchForeClosureCaseAsync(ForeClosureCaseSearchRequest request, object userState) {
            if ((this.SearchForeClosureCaseOperationCompleted == null)) {
                this.SearchForeClosureCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchForeClosureCaseOperationCompleted);
            }
            this.InvokeAsync("SearchForeClosureCase", new object[] {
                        request}, this.SearchForeClosureCaseOperationCompleted, userState);
        }
        
        private void OnSearchForeClosureCaseOperationCompleted(object arg) {
            if ((this.SearchForeClosureCaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchForeClosureCaseCompleted(this, new SearchForeClosureCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.homeownershopenetwork.org", IsNullable=false)]
    public partial class AuthenticationInfo : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class ForeClosureCaseSearchCriteriaDTO {
        
        private string agencyCaseNumberField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string loanNumberField;
        
        private string propertyZipField;
        
        private string last4_SSNField;
        
        /// <remarks/>
        public string AgencyCaseNumber {
            get {
                return this.agencyCaseNumberField;
            }
            set {
                this.agencyCaseNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string LoanNumber {
            get {
                return this.loanNumberField;
            }
            set {
                this.loanNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyZip {
            get {
                return this.propertyZipField;
            }
            set {
                this.propertyZipField = value;
            }
        }
        
        /// <remarks/>
        public string Last4_SSN {
            get {
                return this.last4_SSNField;
            }
            set {
                this.last4_SSNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeClosureCaseSearchRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class BaseRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class ForeClosureCaseSearchRequest : BaseRequest {
        
        private ForeClosureCaseSearchCriteriaDTO searchCriteriaField;
        
        /// <remarks/>
        public ForeClosureCaseSearchCriteriaDTO SearchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class CallLogRetrieveRequest {
        
        private string callLogIdField;
        
        /// <remarks/>
        public string callLogId {
            get {
                return this.callLogIdField;
            }
            set {
                this.callLogIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class ExceptionMessage {
        
        private int exceptionIdField;
        
        private string messageField;
        
        /// <remarks/>
        public int ExceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeClosureCaseSearchResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CallLogRetrieveResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CallLogInsertResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class BaseResponse {
        
        private ExceptionMessage[] messagesField;
        
        private ResponseStatus statusField;
        
        /// <remarks/>
        public ExceptionMessage[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public enum ResponseStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Fail,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        AuthenticationFail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class ForeClosureCaseSearchResponse : BaseResponse {
        
        private ForeClosureCaseWSDTO[] resultsField;
        
        private int searchResultCountField;
        
        /// <remarks/>
        public ForeClosureCaseWSDTO[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public int SearchResultCount {
            get {
                return this.searchResultCountField;
            }
            set {
                this.searchResultCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class ForeClosureCaseWSDTO : BaseDTO {
        
        private int fcIdField;
        
        private System.DateTime intakeDtField;
        
        private string borrowerFnameField;
        
        private string borrowerLnameField;
        
        private string borrowerLast4SSNField;
        
        private string coBorrowerFnameField;
        
        private string coBorrowerLnameField;
        
        private string coBorrowerLast4SSNField;
        
        private string propAddr1Field;
        
        private string propAddr2Field;
        
        private string propCityField;
        
        private string propStateCdField;
        
        private string propZipField;
        
        private string counselorFullNameField;
        
        private string counselorPhoneField;
        
        private string counselorExtField;
        
        private string counselorEmailField;
        
        private System.DateTime completedDtField;
        
        private string bankruptcyIndField;
        
        private string fcNoticeReceivedIndField;
        
        private string agencyCaseNumField;
        
        private string agencyNameField;
        
        private string counseledField;
        
        private System.DateTime delinquentDtField;
        
        private string loanNumberField;
        
        private string loanServicerField;
        
        private string caseLoanIDField;
        
        /// <remarks/>
        public int FcId {
            get {
                return this.fcIdField;
            }
            set {
                this.fcIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime IntakeDt {
            get {
                return this.intakeDtField;
            }
            set {
                this.intakeDtField = value;
            }
        }
        
        /// <remarks/>
        public string BorrowerFname {
            get {
                return this.borrowerFnameField;
            }
            set {
                this.borrowerFnameField = value;
            }
        }
        
        /// <remarks/>
        public string BorrowerLname {
            get {
                return this.borrowerLnameField;
            }
            set {
                this.borrowerLnameField = value;
            }
        }
        
        /// <remarks/>
        public string BorrowerLast4SSN {
            get {
                return this.borrowerLast4SSNField;
            }
            set {
                this.borrowerLast4SSNField = value;
            }
        }
        
        /// <remarks/>
        public string CoBorrowerFname {
            get {
                return this.coBorrowerFnameField;
            }
            set {
                this.coBorrowerFnameField = value;
            }
        }
        
        /// <remarks/>
        public string CoBorrowerLname {
            get {
                return this.coBorrowerLnameField;
            }
            set {
                this.coBorrowerLnameField = value;
            }
        }
        
        /// <remarks/>
        public string CoBorrowerLast4SSN {
            get {
                return this.coBorrowerLast4SSNField;
            }
            set {
                this.coBorrowerLast4SSNField = value;
            }
        }
        
        /// <remarks/>
        public string PropAddr1 {
            get {
                return this.propAddr1Field;
            }
            set {
                this.propAddr1Field = value;
            }
        }
        
        /// <remarks/>
        public string PropAddr2 {
            get {
                return this.propAddr2Field;
            }
            set {
                this.propAddr2Field = value;
            }
        }
        
        /// <remarks/>
        public string PropCity {
            get {
                return this.propCityField;
            }
            set {
                this.propCityField = value;
            }
        }
        
        /// <remarks/>
        public string PropStateCd {
            get {
                return this.propStateCdField;
            }
            set {
                this.propStateCdField = value;
            }
        }
        
        /// <remarks/>
        public string PropZip {
            get {
                return this.propZipField;
            }
            set {
                this.propZipField = value;
            }
        }
        
        /// <remarks/>
        public string CounselorFullName {
            get {
                return this.counselorFullNameField;
            }
            set {
                this.counselorFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string CounselorPhone {
            get {
                return this.counselorPhoneField;
            }
            set {
                this.counselorPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string CounselorExt {
            get {
                return this.counselorExtField;
            }
            set {
                this.counselorExtField = value;
            }
        }
        
        /// <remarks/>
        public string CounselorEmail {
            get {
                return this.counselorEmailField;
            }
            set {
                this.counselorEmailField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CompletedDt {
            get {
                return this.completedDtField;
            }
            set {
                this.completedDtField = value;
            }
        }
        
        /// <remarks/>
        public string BankruptcyInd {
            get {
                return this.bankruptcyIndField;
            }
            set {
                this.bankruptcyIndField = value;
            }
        }
        
        /// <remarks/>
        public string FcNoticeReceivedInd {
            get {
                return this.fcNoticeReceivedIndField;
            }
            set {
                this.fcNoticeReceivedIndField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyCaseNum {
            get {
                return this.agencyCaseNumField;
            }
            set {
                this.agencyCaseNumField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyName {
            get {
                return this.agencyNameField;
            }
            set {
                this.agencyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Counseled {
            get {
                return this.counseledField;
            }
            set {
                this.counseledField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DelinquentDt {
            get {
                return this.delinquentDtField;
            }
            set {
                this.delinquentDtField = value;
            }
        }
        
        /// <remarks/>
        public string LoanNumber {
            get {
                return this.loanNumberField;
            }
            set {
                this.loanNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LoanServicer {
            get {
                return this.loanServicerField;
            }
            set {
                this.loanServicerField = value;
            }
        }
        
        /// <remarks/>
        public string CaseLoanID {
            get {
                return this.caseLoanIDField;
            }
            set {
                this.caseLoanIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeClosureCaseWSDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CallLogWSDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class BaseDTO {
        
        private System.DateTime createDateField;
        
        private string createUserIdField;
        
        private string createAppNameField;
        
        private System.DateTime changeLastDateField;
        
        private string changeLastUserIdField;
        
        private string changeLastAppNameField;
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserId {
            get {
                return this.createUserIdField;
            }
            set {
                this.createUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string CreateAppName {
            get {
                return this.createAppNameField;
            }
            set {
                this.createAppNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ChangeLastDate {
            get {
                return this.changeLastDateField;
            }
            set {
                this.changeLastDateField = value;
            }
        }
        
        /// <remarks/>
        public string ChangeLastUserId {
            get {
                return this.changeLastUserIdField;
            }
            set {
                this.changeLastUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string ChangeLastAppName {
            get {
                return this.changeLastAppNameField;
            }
            set {
                this.changeLastAppNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class CallLogWSDTO : BaseDTO {
        
        private string callIdField;
        
        private string extCallNumberField;
        
        private string agencyIdField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string dNISField;
        
        private string callCenterField;
        
        private string callCenterCDField;
        
        private string callResourceField;
        
        private string reasonToCallField;
        
        private string accountNumberField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string counselPastYRIndField;
        
        private string mtgProbIndField;
        
        private string pastDueIndField;
        
        private string pastDueSoonIndField;
        
        private int pastDueMonthsField;
        
        private int servicerIdField;
        
        private string otherServicerNameField;
        
        private string propZipField;
        
        private int prevCounselorIdField;
        
        private int prevAgencyIdField;
        
        private string selectedAgencyIdField;
        
        private string screenRoutField;
        
        private int finalDispoField;
        
        private string transNumberField;
        
        private string outOfNetworkReferralTBDField;
        
        /// <remarks/>
        public string CallId {
            get {
                return this.callIdField;
            }
            set {
                this.callIdField = value;
            }
        }
        
        /// <remarks/>
        public string ExtCallNumber {
            get {
                return this.extCallNumberField;
            }
            set {
                this.extCallNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyId {
            get {
                return this.agencyIdField;
            }
            set {
                this.agencyIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string DNIS {
            get {
                return this.dNISField;
            }
            set {
                this.dNISField = value;
            }
        }
        
        /// <remarks/>
        public string CallCenter {
            get {
                return this.callCenterField;
            }
            set {
                this.callCenterField = value;
            }
        }
        
        /// <remarks/>
        public string CallCenterCD {
            get {
                return this.callCenterCDField;
            }
            set {
                this.callCenterCDField = value;
            }
        }
        
        /// <remarks/>
        public string CallResource {
            get {
                return this.callResourceField;
            }
            set {
                this.callResourceField = value;
            }
        }
        
        /// <remarks/>
        public string ReasonToCall {
            get {
                return this.reasonToCallField;
            }
            set {
                this.reasonToCallField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string CounselPastYRInd {
            get {
                return this.counselPastYRIndField;
            }
            set {
                this.counselPastYRIndField = value;
            }
        }
        
        /// <remarks/>
        public string MtgProbInd {
            get {
                return this.mtgProbIndField;
            }
            set {
                this.mtgProbIndField = value;
            }
        }
        
        /// <remarks/>
        public string PastDueInd {
            get {
                return this.pastDueIndField;
            }
            set {
                this.pastDueIndField = value;
            }
        }
        
        /// <remarks/>
        public string PastDueSoonInd {
            get {
                return this.pastDueSoonIndField;
            }
            set {
                this.pastDueSoonIndField = value;
            }
        }
        
        /// <remarks/>
        public int PastDueMonths {
            get {
                return this.pastDueMonthsField;
            }
            set {
                this.pastDueMonthsField = value;
            }
        }
        
        /// <remarks/>
        public int ServicerId {
            get {
                return this.servicerIdField;
            }
            set {
                this.servicerIdField = value;
            }
        }
        
        /// <remarks/>
        public string OtherServicerName {
            get {
                return this.otherServicerNameField;
            }
            set {
                this.otherServicerNameField = value;
            }
        }
        
        /// <remarks/>
        public string PropZip {
            get {
                return this.propZipField;
            }
            set {
                this.propZipField = value;
            }
        }
        
        /// <remarks/>
        public int PrevCounselorId {
            get {
                return this.prevCounselorIdField;
            }
            set {
                this.prevCounselorIdField = value;
            }
        }
        
        /// <remarks/>
        public int PrevAgencyId {
            get {
                return this.prevAgencyIdField;
            }
            set {
                this.prevAgencyIdField = value;
            }
        }
        
        /// <remarks/>
        public string SelectedAgencyId {
            get {
                return this.selectedAgencyIdField;
            }
            set {
                this.selectedAgencyIdField = value;
            }
        }
        
        /// <remarks/>
        public string ScreenRout {
            get {
                return this.screenRoutField;
            }
            set {
                this.screenRoutField = value;
            }
        }
        
        /// <remarks/>
        public int FinalDispo {
            get {
                return this.finalDispoField;
            }
            set {
                this.finalDispoField = value;
            }
        }
        
        /// <remarks/>
        public string TransNumber {
            get {
                return this.transNumberField;
            }
            set {
                this.transNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OutOfNetworkReferralTBD {
            get {
                return this.outOfNetworkReferralTBDField;
            }
            set {
                this.outOfNetworkReferralTBDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class CallLogRetrieveResponse : BaseResponse {
        
        private CallLogWSDTO callLogField;
        
        /// <remarks/>
        public CallLogWSDTO CallLog {
            get {
                return this.callLogField;
            }
            set {
                this.callLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class CallLogInsertResponse : BaseResponse {
        
        private string callLogIDField;
        
        /// <remarks/>
        public string CallLogID {
            get {
                return this.callLogIDField;
            }
            set {
                this.callLogIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.homeownershopenetwork.org")]
    public partial class CallLogInsertRequest {
        
        private CallLogWSDTO callLogField;
        
        /// <remarks/>
        public CallLogWSDTO CallLog {
            get {
                return this.callLogField;
            }
            set {
                this.callLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SaveCallLogCompletedEventHandler(object sender, SaveCallLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCallLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCallLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CallLogInsertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CallLogInsertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void RetrieveCallLogCompletedEventHandler(object sender, RetrieveCallLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveCallLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveCallLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CallLogRetrieveResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CallLogRetrieveResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SearchForeClosureCaseCompletedEventHandler(object sender, SearchForeClosureCaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchForeClosureCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchForeClosureCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ForeClosureCaseSearchResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ForeClosureCaseSearchResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591